"""
Setup Wizard - Cấu hình ban đầu cho hệ thống
Hiển thị các bước cấu hình khi chạy lần đầu
"""
import os
import sys
import json
from typing import Dict, Optional

class SetupWizard:
    """Hướng dẫn cấu hình lần đầu"""
    
    # Thông tin API providers
    PROVIDER_GUIDES = {
        "openrouter": {
            "name": "OpenRouter (Recommended)",
            "description": "300+ models từ 50+ providers",
            "api_key_env": "OPENROUTER_API_KEY",
            "register_url": "https://openrouter.ai/settings",
            "free_credit": "$1 free credit when sign up",
            "models_example": ["openai/gpt-4o", "anthropic/claude-sonnet-4.6", "deepseek/deepseek-r1"]
        },
        "openai": {
            "name": "OpenAI (GPT)",
            "description": "GPT-4, GPT-4o models",
            "api_key_env": "OPENAI_API_KEY",
            "register_url": "https://platform.openai.com/api-keys",
            "free_credit": "$5 initial credit",
            "models_example": ["gpt-4o", "gpt-4o-mini", "gpt-5"]
        },
        "anthropic": {
            "name": "Anthropic (Claude)",
            "description": "Claude 4 - Best for coding",
            "api_key_env": "ANTHROPIC_API_KEY",
            "register_url": "https://www.anthropic.com/api",
            "free_credit": "$5 free credits",
            "models_example": ["claude-sonnet-4-20250514", "claude-opus-4-20250514"]
        },
        "google": {
            "name": "Google Gemini",
            "description": "Gemini 2.5 - Fast & Cheap",
            "api_key_env": "GEMINI_API_KEY",
            "register_url": "https://aistudio.google.com/app/apikey",
            "free_credit": "15 RPM, 1500 TPM free",
            "models_example": ["gemini-2.0-flash", "gemini-1.5-pro"]
        },
        "deepseek": {
            "name": "DeepSeek",
            "description": "Free & Open Source Models",
            "api_key_env": "DEEPSEEK_API_KEY",
            "register_url": "https://platform.deepseek.com",
            "free_credit": "Completely free",
            "models_example": ["deepseek-chat", "deepseek-coder", "deepseek-reasoner"]
        },
        "groq": {
            "name": "Groq",
            "description": "Fastest inference",
            "api_key_env": "GROQ_API_KEY",
            "register_url": "https://console.groq.com",
            "free_credit": "Free tier available",
            "models_example": ["llama-3.3-70b-versatile", "mixtral-8x7b-32768"]
        },
        "together": {
            "name": "Together AI",
            "description": "Best open source models",
            "api_key_env": "TOGETHER_API_KEY",
            "register_url": "https://together.ai",
            "free_credit": "$25 credit for new users",
            "models_example": ["Llama-3.3-70B-Instruct", "Qwen2.5-72B-Instruct"]
        }
    }
    
    # Modules cần cấu hình
    MODULES = {
        "ai_brain": {
            "name": "AI Brain",
            "description": "Dùng AI phân tích thị trường",
            "required": True,
            "providers": ["openrouter", "openai", "anthropic", "google", "deepseek", "groq", "together"]
        },
        "exchange": {
            "name": "Exchange API",
            "description": "Kết nối sàn (Binance, OKX, Bybit)",
            "required": False,
            "providers": ["binance", "okx", "bybit"]
        },
        "rpc": {
            "name": "Solana RPC",
            "description": "Đọc dữ liệu on-chain",
            "required": False,
            "providers": ["helius", "quicknode", "public"]
        },
        "wallet": {
            "name": "Wallet Tracking",
            "description": "Theo dõi ví Whale",
            "required": False,
            "providers": ["phantom", "solflare"]
        }
    }
    
    def __init__(self):
        self.config_file = "config/.env"
        self.config = {}
        self._load_existing_config()
    
    def _load_existing_config(self):
        """Load existing config"""
        if os.path.exists(self.config_file):
            with open(self.config_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and '=' in line and not line.startswith('#'):
                        key, value = line.split('=', 1)
                        self.config[key.strip()] = value.strip()
    
    def _save_config(self):
        """Save config"""
        os.makedirs("config", exist_ok=True)
        with open(self.config_file, 'w') as f:
            f.write("# QFD Configuration\n")
            f.write("# Generated by Setup Wizard\n\n")
            for key, value in self.config.items():
                if value:
                    f.write(f"{key}={value}\n")
    
    def run(self):
        """Chạy setup wizard"""
        print("\n" + "="*60)
        print("🚀 WELCOME TO QUANT FOR DONKEY")
        print("="*60)
        print("\nThiết lập hệ thống lần đầu...")
        
        # Check if already configured
        if self._is_configured():
            print("\n✅ Hệ thống đã được cấu hình trước đó.")
            return
        
        # Step 1: AI Provider
        self._setup_ai_provider()
        
        # Step 2: Exchange (optional)
        self._setup_exchange()
        
        # Step 3: RPC (optional)
        self._setup_rpc()
        
        # Save
        self._save_config()
        
        print("\n" + "="*60)
        print("✅ SETUP HOÀN TẤT!")
        print("="*60)
    
    def _is_configured(self) -> bool:
        """Check if already has AI config"""
        for key in ["OPENROUTER_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY", 
                 "GEMINI_API_KEY", "DEEPSEEK_API_KEY"]:
            if self.config.get(key):
                return True
        return False
    
    def _setup_ai_provider(self):
        """Cấu hình AI Provider"""
        print("\n" + "-"*40)
        print("📡 BƯỚC 1: CẤU HÌNH AI PROVIDER")
        print("-"*40)
        print("\nChọn AI provider (điền số):")
        
        for i, (key, info) in enumerate(self.PROVIDER_GUIDES.items(), 1):
            print(f"  {i}. {info['name']}")
            print(f"     → {info['description']}")
            print(f"     → Đăng ký: {info['register_url']}")
            print(f"     → Miễn phí: {info['free_credit']}")
        
        print("\n  0. SKIP - B��� qua bước này")
        
        while True:
            try:
                choice = input("\n👉 Chọn provider [0-7]: ").strip()
                if choice == "0":
                    print("⏭️  Đã bỏ qua bước AI Provider")
                    return
                
                idx = int(choice) - 1
                if 0 <= idx < len(self.PROVIDER_GUIDES):
                    provider_key = list(self.PROVIDER_GUIDES.keys())[idx]
                    info = self.PROVIDER_GUIDES[provider_key]
                    break
            except:
                pass
        
        # Get API key
        print(f"\n📋 Để lấy API Key:")
        print(f"   1. Truy cập: {info['register_url']}")
        print(f"   2. Đăng ký/Đăng nhập")
        print(f"   3. Tạo API Key")
        print(f"   4. Copy và dán bên dưới")
        
        api_key = input(f"\n🔑 Nhập {info['name']} API Key: ").strip()
        
        if api_key:
            self.config[info['api_key_env']] = api_key
            # Save immediately
            self._save_config()
            print(f"\n✅ Đã lưu {info['name']} API Key")
        else:
            print("⏭️  Đã bỏ qua")
    
    def _setup_exchange(self):
        """Cấu hình Exchange (optional)"""
        print("\n" + "-"*40)
        print("💰 BƯỚC 2: EXCHANGE API (Optional)")
        print("-"*40)
        print("Bỏ qua nếu chỉ dùng để phân tích (không trade thật)")
        print("  0. SKIP")
        print("  1. Binance")
        print("  2. OKX")
        print("  3. Bybit")
        
        choice = input("\n👉 Chọn [0-3]: ").strip()
        
        if choice == "0" or not choice:
            print("⏭️  Đã bỏ qua")
            return
        
        exchanges = {"1": "BINANCE", "2": "OKX", "3": "BYBIT"}
        exch = exchanges.get(choice)
        
        if exch:
            api_key = input(f"  API Key: ").strip()
            secret = input(f"  Secret Key: ").strip()
            
            if api_key and secret:
                self.config[f"{exch}_API_KEY"] = api_key
                self.config[f"{exch}_SECRET_KEY"] = secret
                print(f"✅ Đã lưu {exch} credentials")
    
    def _setup_rpc(self):
        """Cấu hình RPC (optional)"""
        print("\n" + "-"*40)
        print("🔗 BƯỚC 3: SOLANA RPC (Optional)")
        print("-"*40)
        print("Dùng để đọc dữ liệu on-chain")
        print("  0. SKIP - Dùng RPC miễn phí")
        print("  1. Helius (Free: 100k/day)")
        print("  2. QuickNode (Free: 100k/month)")
        
        choice = input("\n👉 Chọn [0-2]: ").strip()
        
        if choice == "0" or not choice:
            print("⏭️  Sẽ dùng RPC miễn phí")
            return
        
        rpcs = {"1": "HELIUS", "2": "QUICKNODE"}
        rpc = rpcs.get(choice)
        
        if rpc:
            api_key = input(f"  {rpc} API Key: ").strip()
            
            if api_key:
                self.config[f"{rpc}_API_KEY"] = api_key
                print(f"✅ Đã lưu {rpc} API Key")
    
    def check_status(self) -> Dict:
        """Kiểm tra trạng thái config"""
        status = {}
        
        # AI Providers
        ai_providers = []
        for key, info in self.PROVIDER_GUIDES.items():
            if self.config.get(info['api_key_env']):
                ai_providers.append(info['name'])
        status['ai_provider'] = ai_providers if ai_providers else None
        
        # Exchange
        for ex in ['BINANCE', 'OKX', 'BYBIT']:
            if self.config.get(f"{ex}_API_KEY"):
                status['exchange'] = ex
                break
        
        # RPC
        for rpc in ['HELIUS', 'QUICKNODE']:
            if self.config.get(f"{rpc}_API_KEY"):
                status['rpc'] = rpc
                break
        
        return status


def run_setup():
    """Chạy setup"""
    wizard = SetupWizard()
    wizard.run()
    return wizard.check_status()


if __name__ == "__main__":
    status = run_setup()
    print("\n📊 Config Status:", status)